apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed-issuer
  namespace: vault
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: vault
spec:
  isCA: true
  commonName: root-ca
  secretName: tls-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: vault
spec:
  ca:
    secretName: tls-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-crt
  namespace: vault
spec:
  isCA: false
  commonName: vault-internal
  secretName: tls-server
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 720h
  renewBefore: 360h
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
