apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signed-issuer
  namespace: vault
  labels:
    app: vault
spec:
  selfSigned: {}
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: self-signed-issuer-policy
  namespace: vault
  labels:
    app: vault
spec:
  allowed:
    isCA: true
    commonName:
      required: true
      value: "*"
  constraints:
    maxDuration: 6260h
  selector:
    issuerRef:
      name: self-signed-issuer
      kind: Issuer
      group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca
  namespace: vault
  labels:
    app: vault
spec:
  isCA: true
  commonName: root-ca
  secretName: tls-ca
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: self-signed-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: vault
  labels:
    app: vault
spec:
  ca:
    secretName: tls-ca
---
apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: ca-issuer-policy
  namespace: vault
  labels:
    app: vault
spec:
  allowed:
    isCA: false
    commonName:
      required: true
      value: "*"
    dnsNames:
      required: true
      values: ["*.vault-internal"]
  constraints:
    maxDuration: "360h"
  selector:
    issuerRef:
      name: ca-issuer
      kind: Issuer
      group: cert-manager.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-policy:user
  labels:
    app: vault
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-policy:user-binding
  labels:
    app: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-policy:user
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-server-crt
  namespace: vault
  labels:
    app: vault
spec:
  isCA: false
  commonName: vault-internal
  dnsNames:
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
  secretName: tls-server
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 360h
  renewBefore: 180h
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
